import React, { useEffect, useRef, useState, forwardRef, useImperativeHandle } from "react";
import { TextRotator } from "../common/buttons/TextRotator";
import { RevealOnScroll } from "../RevealOnScroll";
import PlayIcon from "../common/icons/PlayIcon";

export const Home = () => {
  const rotatorRef = useRef(null);

  const [isStarted, setIsStarted] = useState(false);

  const groups = [
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good", letterDelay: 1, displayDuration: 6 },
    { text: "yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 },
    { text: "Baby", letterDelay: 1, displayDuration: 6 },
    { text: "I'ma", letterDelay: 1, displayDuration: 4 },
    { text: "have", letterDelay: 1, displayDuration: 4 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "best", letterDelay: 1, displayDuration: 4 },
    { text: "fuckin'", letterDelay: 1, displayDuration: 8 },
    { text: "night", letterDelay: 1, displayDuration: 6 },
    { text: "of", letterDelay: 1, displayDuration: 3 },
    { text: "my", letterDelay: 1, displayDuration: 3 },
    { text: "life", letterDelay: 1, displayDuration: 4 },
    { text: "And", letterDelay: 1, displayDuration: 3 },
    { text: "wherever", letterDelay: 1, displayDuration: 9 },
    { text: "it", letterDelay: 1, displayDuration: 3 },
    { text: "takes", letterDelay: 1, displayDuration: 6 },
    { text: "me", letterDelay: 1, displayDuration: 3 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "down", letterDelay: 1, displayDuration: 4 },
    { text: "for", letterDelay: 1, displayDuration: 3 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "ride", letterDelay: 1, displayDuration: 4 },
    { text: "Baby", letterDelay: 1, displayDuration: 6 },
    { text: "don't", letterDelay: 1, displayDuration: 4 },
    { text: "you", letterDelay: 1, displayDuration: 3 },
    { text: "know", letterDelay: 1, displayDuration: 4 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good?", letterDelay: 1, displayDuration: 6 },
    { text: "Yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 },
    { text: "", letterDelay: 0, displayDuration: 7, isPause: true },
    { text: "'Cause", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good", letterDelay: 1, displayDuration: 6 },
    { text: "yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 },
    { text: "Baby", letterDelay: 1, displayDuration: 6 },
    { text: "I'ma", letterDelay: 1, displayDuration: 4 },
    { text: "have", letterDelay: 1, displayDuration: 4 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "best", letterDelay: 1, displayDuration: 4 },
    { text: "fuckin'", letterDelay: 1, displayDuration: 8 },
    { text: "night", letterDelay: 1, displayDuration: 6 },
    { text: "of", letterDelay: 1, displayDuration: 3 },
    { text: "my", letterDelay: 1, displayDuration: 3 },
    { text: "life", letterDelay: 1, displayDuration: 4 },
    { text: "And", letterDelay: 1, displayDuration: 3 },
    { text: "wherever", letterDelay: 1, displayDuration: 9 },
    { text: "it", letterDelay: 1, displayDuration: 3 },
    { text: "takes", letterDelay: 1, displayDuration: 6 },
    { text: "me", letterDelay: 1, displayDuration: 3 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "down", letterDelay: 1, displayDuration: 4 },
    { text: "for", letterDelay: 1, displayDuration: 3 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "ride", letterDelay: 1, displayDuration: 4 },
    { text: "Baby", letterDelay: 1, displayDuration: 6 },
    { text: "don't", letterDelay: 1, displayDuration: 4 },
    { text: "you", letterDelay: 1, displayDuration: 3 },
    { text: "know", letterDelay: 1, displayDuration: 4 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good?", letterDelay: 1, displayDuration: 6 },
    { text: "Yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 },
    { text: "", letterDelay: 0, displayDuration: 7, isPause: true },
    { text: "Don't", letterDelay: 1, displayDuration: 4 },
    { text: "you", letterDelay: 1, displayDuration: 3 },
    { text: "know", letterDelay: 1, displayDuration: 4 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good?", letterDelay: 1, displayDuration: 6 },
    { text: "Yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 },
    { text: "", letterDelay: 0, displayDuration: 7, isPause: true },
    { text: "You", letterDelay: 1, displayDuration: 3 },
    { text: "know", letterDelay: 1, displayDuration: 4 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "down", letterDelay: 1, displayDuration: 4 },
    { text: "for", letterDelay: 1, displayDuration: 3 },
    { text: "whatever", letterDelay: 1, displayDuration: 9 },
    { text: "tonight", letterDelay: 1, displayDuration: 7 },
    { text: "I", letterDelay: 1, displayDuration: 3 },
    { text: "don't", letterDelay: 1, displayDuration: 4 },
    { text: "need", letterDelay: 1, displayDuration: 4 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "finer", letterDelay: 1, displayDuration: 6 },
    { text: "things", letterDelay: 1, displayDuration: 6 },
    { text: "in", letterDelay: 1, displayDuration: 3 },
    { text: "life", letterDelay: 1, displayDuration: 4 },
    { text: "No", letterDelay: 1, displayDuration: 3 },
    { text: "matter", letterDelay: 1, displayDuration: 6 },
    { text: "where", letterDelay: 1, displayDuration: 4 },
    { text: "I", letterDelay: 1, displayDuration: 3 },
    { text: "go", letterDelay: 1, displayDuration: 3 },
    { text: "it's", letterDelay: 1, displayDuration: 3 },
    { text: "a", letterDelay: 1, displayDuration: 3 },
    { text: "good", letterDelay: 1, displayDuration: 4 },
    { text: "time", letterDelay: 1, displayDuration: 4 },
    { text: "yeah", letterDelay: 1, displayDuration: 3 },
    { text: "And", letterDelay: 1, displayDuration: 3 },
    { text: "I", letterDelay: 1, displayDuration: 3 },
    { text: "I", letterDelay: 1, displayDuration: 3 },
    { text: "don't", letterDelay: 1, displayDuration: 4 },
    { text: "need", letterDelay: 1, displayDuration: 4 },
    { text: "to", letterDelay: 1, displayDuration: 3 },
    { text: "sit", letterDelay: 1, displayDuration: 3 },
    { text: "in", letterDelay: 1, displayDuration: 3 },
    { text: "VIP", letterDelay: 1, displayDuration: 3 },
    { text: "Middle", letterDelay: 1, displayDuration: 6 },
    { text: "of", letterDelay: 1, displayDuration: 3 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "floor", letterDelay: 1, displayDuration: 4 },
    { text: "that's", letterDelay: 1, displayDuration: 4 },
    { text: "where", letterDelay: 1, displayDuration: 4 },
    { text: "I'll", letterDelay: 1, displayDuration: 3 },
    { text: "be", letterDelay: 1, displayDuration: 3 },
    { text: "Don't", letterDelay: 1, displayDuration: 4 },
    { text: "got", letterDelay: 1, displayDuration: 3 },
    { text: "a", letterDelay: 1, displayDuration: 3 },
    { text: "lot", letterDelay: 1, displayDuration: 3 },
    { text: "but", letterDelay: 1, displayDuration: 3 },
    { text: "that's", letterDelay: 1, displayDuration: 4 },
    { text: "enough", letterDelay: 1, displayDuration: 7 },
    { text: "for", letterDelay: 1, displayDuration: 3 },
    { text: "me", letterDelay: 1, displayDuration: 3 },
    { text: "yeah", letterDelay: 1, displayDuration: 3 },
    { text: "", letterDelay: 0, displayDuration: 7, isPause: true },
    { text: "'Cause", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good", letterDelay: 1, displayDuration: 6 },
    { text: "yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 },
    { text: "Baby", letterDelay: 1, displayDuration: 6 },
    { text: "I'ma", letterDelay: 1, displayDuration: 4 },
    { text: "have", letterDelay: 1, displayDuration: 4 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "best", letterDelay: 1, displayDuration: 4 },
    { text: "fuckin'", letterDelay: 1, displayDuration: 8 },
    { text: "night", letterDelay: 1, displayDuration: 6 },
    { text: "of", letterDelay: 1, displayDuration: 3 },
    { text: "my", letterDelay: 1, displayDuration: 3 },
    { text: "life", letterDelay: 1, displayDuration: 4 },
    { text: "And", letterDelay: 1, displayDuration: 3 },
    { text: "wherever", letterDelay: 1, displayDuration: 9 },
    { text: "it", letterDelay: 1, displayDuration: 3 },
    { text: "takes", letterDelay: 1, displayDuration: 6 },
    { text: "me", letterDelay: 1, displayDuration: 3 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "down", letterDelay: 1, displayDuration: 4 },
    { text: "for", letterDelay: 1, displayDuration: 3 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "ride", letterDelay: 1, displayDuration: 4 },
    { text: "Baby", letterDelay: 1, displayDuration: 6 },
    { text: "don't", letterDelay: 1, displayDuration: 4 },
    { text: "you", letterDelay: 1, displayDuration: 3 },
    { text: "know", letterDelay: 1, displayDuration: 4 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good?", letterDelay: 1, displayDuration: 6 },
    { text: "Yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 },
    { text: "", letterDelay: 0, displayDuration: 7, isPause: true },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good", letterDelay: 1, displayDuration: 4 },
    { text: "Good", letterDelay: 1, displayDuration: 4 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good", letterDelay: 1, displayDuration: 4 },
    { text: "Don't", letterDelay: 1, displayDuration: 4 },
    { text: "you", letterDelay: 1, displayDuration: 3 },
    { text: "know", letterDelay: 1, displayDuration: 4 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good?", letterDelay: 1, displayDuration: 6 },
    { text: "Yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 },
    { text: "", letterDelay: 0, displayDuration: 7, isPause: true },
    { text: "So", letterDelay: 1, displayDuration: 3 },
    { text: "I", letterDelay: 1, displayDuration: 3 },
    { text: "just", letterDelay: 1, displayDuration: 3 },
    { text: "let", letterDelay: 1, displayDuration: 3 },
    { text: "it", letterDelay: 1, displayDuration: 3 },
    { text: "go", letterDelay: 1, displayDuration: 3 },
    { text: "let", letterDelay: 1, displayDuration: 3 },
    { text: "it", letterDelay: 1, displayDuration: 3 },
    { text: "go", letterDelay: 1, displayDuration: 3 },
    { text: "Oh", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "No", letterDelay: 1, displayDuration: 3 },
    { text: "I", letterDelay: 1, displayDuration: 3 },
    { text: "don't", letterDelay: 1, displayDuration: 4 },
    { text: "care", letterDelay: 1, displayDuration: 4 },
    { text: "no", letterDelay: 1, displayDuration: 3 },
    { text: "more", letterDelay: 1, displayDuration: 3 },
    { text: "care", letterDelay: 1, displayDuration: 4 },
    { text: "no", letterDelay: 1, displayDuration: 3 },
    { text: "more", letterDelay: 1, displayDuration: 3 },
    { text: "Oh", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "So", letterDelay: 1, displayDuration: 3 },
    { text: "come", letterDelay: 1, displayDuration: 3 },
    { text: "on", letterDelay: 1, displayDuration: 3 },
    { text: "let", letterDelay: 1, displayDuration: 3 },
    { text: "me", letterDelay: 1, displayDuration: 3 },
    { text: "know", letterDelay: 1, displayDuration: 3 },
    { text: "let", letterDelay: 1, displayDuration: 3 },
    { text: "me", letterDelay: 1, displayDuration: 3 },
    { text: "know", letterDelay: 1, displayDuration: 3 },
    { text: "Put", letterDelay: 1, displayDuration: 3 },
    { text: "your", letterDelay: 1, displayDuration: 3 },
    { text: "hands", letterDelay: 1, displayDuration: 6 },
    { text: "up", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "na", letterDelay: 1, displayDuration: 3 },
    { text: "No", letterDelay: 1, displayDuration: 3 },
    { text: "baby", letterDelay: 1, displayDuration: 6 },
    { text: "nothing's", letterDelay: 1, displayDuration: 9 },
    { text: "gonna", letterDelay: 1, displayDuration: 4 },
    { text: "stop", letterDelay: 1, displayDuration: 4 },
    { text: "us", letterDelay: 1, displayDuration: 3 },
    { text: "tonight", letterDelay: 1, displayDuration: 7 },
    { text: "", letterDelay: 0, displayDuration: 7, isPause: true },
    { text: "'Cause", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good", letterDelay: 1, displayDuration: 6 },
    { text: "yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 },
    { text: "Baby", letterDelay: 1, displayDuration: 6 },
    { text: "I'ma", letterDelay: 1, displayDuration: 4 },
    { text: "have", letterDelay: 1, displayDuration: 4 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "best", letterDelay: 1, displayDuration: 4 },
    { text: "fuckin'", letterDelay: 1, displayDuration: 8 },
    { text: "night", letterDelay: 1, displayDuration: 6 },
    { text: "of", letterDelay: 1, displayDuration: 3 },
    { text: "my", letterDelay: 1, displayDuration: 3 },
    { text: "life", letterDelay: 1, displayDuration: 4 },
    { text: "And", letterDelay: 1, displayDuration: 3 },
    { text: "wherever", letterDelay: 1, displayDuration: 9 },
    { text: "it", letterDelay: 1, displayDuration: 3 },
    { text: "takes", letterDelay: 1, displayDuration: 6 },
    { text: "me", letterDelay: 1, displayDuration: 3 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "down", letterDelay: 1, displayDuration: 4 },
    { text: "for", letterDelay: 1, displayDuration: 3 },
    { text: "the", letterDelay: 1, displayDuration: 3 },
    { text: "ride", letterDelay: 1, displayDuration: 4 },
    { text: "Baby", letterDelay: 1, displayDuration: 6 },
    { text: "don't", letterDelay: 1, displayDuration: 4 },
    { text: "you", letterDelay: 1, displayDuration: 3 },
    { text: "know", letterDelay: 1, displayDuration: 4 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "good?", letterDelay: 1, displayDuration: 6 },
    { text: "Yeah", letterDelay: 1, displayDuration: 6 },
    { text: "I'm", letterDelay: 1, displayDuration: 3 },
    { text: "feelin'", letterDelay: 1, displayDuration: 8 },
    { text: "alright", letterDelay: 1, displayDuration: 8 }
  ];

  function handleStart() {
    if (!rotatorRef.current || typeof rotatorRef.current.startSequence !== "function") return;
    setIsStarted(true);
    rotatorRef.current.startSequence(0);
  }

  function handleOnIndexChange(idx) {
    setCurrentIndex(idx);
  }

  function handleOnEnd() {
    setIsStarted(false);
  }

  return (
    <section id="home" className="min-h-screen flex items-center justify-center relative">
      <RevealOnScroll>
        <div className="text-center z-10 px-4">
          <div className="mb-8">
            <TextRotator
              ref={rotatorRef}
              groups={groups}
              defaultLetterDelay={50}
              defaultDisplayDuration={1500}
              transitionDuration={450}
              onIndexChange={handleOnIndexChange}
              onEnd={handleOnEnd}
            />
          </div>

          <div className="mt-6 flex items-center justify-center gap-4">
            <button
              onClick={handleStart}
              disabled={isStarted}
              className={`px-4 py-2 rounded-md text-white font-semibold transition ${isStarted ? 'opacity-50 cursor-not-allowed bg-gray-500' : 'bg-red-600 hover:bg-red-700'}`}
            >
              {isStarted ? <PlayIcon type={2} /> : <PlayIcon type={1} />}
            </button>
          </div>
        </div>
      </RevealOnScroll>
    </section>
  );
};

export default Home;
